name: build
on:
  workflow_dispatch:
    inputs:
      version:
        description: snapcast version to build
        required: true
        default: master
jobs:
  docker:
    name: ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        if: steps.compare_versions.outputs.trigger_workflow == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.actor }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # arm/v6,7,8: https://github.com/alpinelinux/docker-alpine/issues/135
          # Alpine 3.13.0+ requires: libseccomp 2.4.2 _and_ docker engine v19.04+
          # https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.event.inputs.version }}
          tags: ghcr.io/${{steps.string.outputs.lowercase}}/snapserver:${{ github.event.inputs.version }},ghcr.io/${{steps.string.outputs.lowercase}}/snapserver:latest
