name: build
on:
  workflow_dispatch:
    inputs:
      version:
        description: snapcast version to build
        required: true
        default: master
jobs:
  docker:
    name: ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # arm/v6,7,8: https://github.com/alpinelinux/docker-alpine/issues/135
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ github.event.inputs.version }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/snapcast:${{ github.event.inputs.version }},${{ secrets.DOCKERHUB_USERNAME }}/snapcast:latest
